# Scraper scheduler
[job-exec "scraper-index-articles-task"]
schedule = @every 4h
container = scraper
command = python -m src.data.scraping.index_articles
no-overlap = true

[job-exec "scraper-enrich-articles-task"]
schedule = @every 2h
container = scraper
command = python -m src.data.scraping.enrich_articles
no-overlap = true

[job-exec "scraper-detect-symbols-task"]
schedule = @every 1h
container = scraper
command = python -m src.data.scraping.detect_symbols
no-overlap = true

[job-exec "scraper-feature-sentiment-task"]
schedule = @every 1h
container = scraper-feature-sentiment
command = python -m src.features.scraping.sentiment
no-overlap = true

[job-exec "data-transformer-task"]
schedule = @every 10s
container = data-transformer
command = python -m src.data.binance.transform_and_load --incremental
no-overlap = true

[job-exec "features-compute-features-task"]
schedule = @every 1m
container = features-compute-features
command = bash src/features/compute_features.sh
no-overlap = true

[job-exec "features-compute-labels-task"]
schedule = @every 1m
container = features-compute-labels
command = bash src/features/labels/compute_labels.sh
no-overlap = true

[job-exec "models-predict-task"]
schedule = @every 1m
container = models-predict
command = bash src/models/predict_model.sh
no-overlap = true

