# Scraper scheduler
[job-exec "scraper-index-articles-task"]
schedule = @every 4h
container = scraper
command = python -m src.data.scraping.index_articles
no-overlap = true

[job-exec "scraper-enrich-articles-task"]
schedule = @every 2h
container = scraper
command = python -m src.data.scraping.enrich_articles
no-overlap = true

[job-exec "scraper-detect-symbols-task"]
schedule = @every 1h
container = scraper
command = python -m src.data.scraping.detect_symbols
no-overlap = true

[job-exec "scraper-feature-sentiment-task"]
schedule = @every 1h
container = scraper-feature-sentiment
command = python -m src.features.scraping.sentiment
no-overlap = true